### ISSUE TITLE
backend module "About Modules" broken when phpunit is installed

### ISSUE THREAD

**Issue by hannesbochmann** [oliverklee/ext-phpunit#3]
I get the following exception when I open "About Modules" and phpunit is installed (current master):

TYPO3Fluid\Fluid\Core\Exception
      message => 'An argument "key" or "id" has to be provided'
      code => 1351584844
      file => '/var/www/html/vendor/typo3/cms/typo3/sysext/fluid/Classes/ViewHelpers/TranslateViewHelper.php'
      line => 133

I can also provide a complete stack trace if you like.

**Comment by oliverklee** [comment]
Which version of TYPO3 are you using? And which version of phpunit are you using? And are you using TYPO3 in Composer mode or classic mode?

Yes, a stack trace would also be helpful.

**Comment by hannesbochmann** [comment]
phpunit in the current master version
TYPO3 8.7.9
composer mode = yes

Stack trace:

0 require(typo3/cms/typo3/sysext/backend/Resources/Private/Php/backend.php),typo3/cms/typo3/index.php#3
1 {closure}#25
2 TYPO3\CMS\Backend\Http\Application->run#24
3 TYPO3\CMS\Core\Core\Bootstrap->handleRequest#92
4 TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->handleRequest#315
5 TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->dispatchModule#89
6 TYPO3\CMS\Extbase\Core\Bootstrap->run#182
7 TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest#186
8 TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRequest#199
9 TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch#32
10 TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest#85
11 TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod#176
12 TYPO3\CMS\Backend\View\BackendTemplateView->render#345
13 TYPO3Fluid\Fluid\View\AbstractTemplateView->render#76
14 layout_Default_html_4dff6ad07ab265c6f88b16b071a26bed43a292cf->render#200
15 TYPO3Fluid\Fluid\ViewHelpers\RenderViewHelper::renderStatic#76
16 TYPO3Fluid\Fluid\View\AbstractTemplateView->renderSection#143
17 Modules_action_index_41298b8b2e91a7a9d9ae1545a025754664a9508b->section_4f9be057f0ea5d2ba72fd2c810e8d7b9aa98b469#249
18 TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper::renderStatic#578
19 Modules_action_index_41298b8b2e91a7a9d9ae1545a025754664a9508b->{closure}#133
20 TYPO3Fluid\Fluid\Core\ViewHelper\AbstractConditionViewHelper::renderStatic#562
21 Modules_action_index_41298b8b2e91a7a9d9ae1545a025754664a9508b->{closure}#85
22 TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper::renderStatic#536
23 Modules_action_index_41298b8b2e91a7a9d9ae1545a025754664a9508b->{closure}#133
24 TYPO3\CMS\Fluid\ViewHelpers\TranslateViewHelper::renderStatic#230

**Comment by oliverklee** [comment]
Thanks for the additional information!

The BE module is not compatible with TYPO3 CMS 8.7.x (and won't be as it's conceptionally flawed). Sorry. In the current phpunit master, the BE module is disabled now.

Please use the CLI test runner for TYPO3 CMS >= 8.7.

**Comment by sushilkumargupta** [comment]
Hi Oliver Klee,
 
Since I cannot see any link for PHP Unit in Backend module of Typo3 8.7, so that can you whare with my the code about how to run a test file from command line. 
Apart from this when I execute the following code then it shows me an error message:
$ sudo php /var/www/html/fabdyl/typo3/sysext/core/bin/typo3 phpunit:run /var/www/html/demo87/typo3conf/ext/viemployee/Tests/Unit/Controller/EmployeeControllerTest.php
Oops, an error occurred: This supplied command is not valid.
Valid keys are:
  extbase
  lowlevel_cleaner"
So, can you with please share with me a code you execute unit test from command line?

**Comment by oliverklee** [comment]
@sushilkumargupta Could you please check that the phpunit extension is installed?

**Comment by sushilkumargupta** [comment]
Hi Oliver Klee,

Thank you for your quick reply.
It is showing in "Installed Extensions" list. Please check the attached screenshot.
![phpunit_installed](https://user-images.githubusercontent.com/6986909/46205934-10ae9400-c340-11e8-8f2f-3d3518efcaa4.png)

Thanks,
Sushil Gupta

**Comment by oliverklee** [comment]
This is the output I get when listing all commands:

```
klee@gonzales:~/public_html/typo387.local$ typo3/sysext/core/bin/typo3 list
TYPO3 CMS 8.7.20-dev

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help                                                    Displays help for a command
  list                                                    Lists commands
 backend
  backend:lock                                            Lock the TYPO3 Backend
  backend:unlock                                          Unlock the TYPO3 Backend
 cleanup
  cleanup:deletedrecords                                  Permanently deletes all records marked as "deleted" in the database.
  cleanup:flexforms                                       Updates all database records which have a FlexForm field and the XML data does not match the chosen datastructure.
  cleanup:lostfiles                                       Looking for files in the uploads/ folder which does not have a reference in TYPO3 managed records.
  cleanup:missingfiles                                    Find all file references from records pointing to a missing (non-existing) file.
  cleanup:missingrelations                                Find all record references pointing to a non-existing record
  cleanup:multiplereferencedfiles                         Looking for files from TYPO3 managed records which are referenced more than once
  cleanup:orphanrecords                                   Find and delete records that have lost their connection with the page tree.
  cleanup:rteimages                                       Looking up all occurrences of RTEmagic images in the database and check existence of parent and copy files on the file system plus report possibly lost RTE files.
  cleanup:versions                                        Find all versioned records and possibly cleans up invalid records in the database.
 extbase
  extbase:help:help                                       [extbase:help] The help command displays help for a given command: ./typo3/sysext/core/bin/typo3 extbase:help <command identifier>
 extensionmanager
  extensionmanager:extension:dumpclassloadinginformation  [extension:dumpclassloadinginformation] This command is only needed during development. The extension manager takes care creating or updating this info properly during extension (de-)activation.
  extensionmanager:extension:install                      [extension:install] The extension files must be present in one of the recognised extension folder paths in TYPO3.
  extensionmanager:extension:uninstall                    [extension:uninstall] The extension files must be present in one of the recognised extension folder paths in TYPO3.
 lang                                                                                                                                                                                                     
  lang:language:update                                    [language:update]                                                                                                                               
 phpunit                                                                                                                                                                                                  
  phpunit:run                                             Runs PHPUnit tests from the command line.                                                                                                       
 referenceindex                                                                                                                                                                                           
  referenceindex:update                                   Update the reference index of TYPO3                                                                                                             
 scheduler                                                                                                                                                                                                
  scheduler:run                                           Start the TYPO3 Scheduler from the command line.                                                                                                
 syslog                                                                                                                                                                                                   
  syslog:list                                             Show entries from the sys_log database table of the last 24 hours.                                                                              
```

This is the command to run the tests on the command line in 8.7: https://docs.typo3.org/typo3cms/extensions/phpunit/UsersManual/RunningTheUnitTestsOnTheCommandLine/Index.html

So it seems something is broken in your installation, but I don't know what. I can't you help with this from here. Sorry.
