### ISSUE TITLE
Set the DB name in the connection pool in TYPO3 8.7

### ISSUE THREAD

**Issue by hannesbochmann** [oliverklee/ext-phpunit#54]
I have a database testcase that calls the rootline utility in the background. The rootline utility won't give me the data from the test database but from the real database. This is because the rootline utility uses this code the get the database connection:
GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable('pages');

This will always return a connection which uses the real database configuration.

phpunit selects the test database only for $GLOBALS['TYPO3_DB'] but not for the new connection pools. Do you see any solution to this problem?

**Comment by hannesbochmann** [comment]
tested in TYPO3 8.7 and PHP 7.1

**Comment by oliverklee** [comment]
We'll need to adapt PHPUnit to use the new ConnectionPool and the QueryBuilder in 8.7.

**Comment by hannesbochmann** [comment]
So this means database tests with phpunit are currently not working 100%?

**Comment by oliverklee** [comment]
> So this means database tests with phpunit are currently not working 100%?

DB tests don't work 100% when using TYPO3 >= 8.7 and when the tested code uses the ConnectionPool and QueryBuilder.

**Comment by felixsemmler** [comment]
@hannesbochmann 
Maybe this works for you too:
https://github.com/AOEpeople/ext-phpunit/commit/522fc0c840bcced99d91ade8aefc76e1ded28ef7

Our DB tests run with this commit.

**Comment by oliverklee** [comment]
@felixsemmler Would you be willing to create a PR for this change here?

**Comment by felixsemmler** [comment]
> @felixsemmler Would you be willing to create a PR for this change here?

Hi, we actually try to migrate our two old extensions which uses the ext-phpunit to the nimut-testing-framework. For one extensions we could manage the migration. I got the unittests green for the extensions which depends still on ext-phpunit, but my changes causes a failure in travis, because I don't adapt the unittests of ext-phpunit. I had actually not the time to fix or adapt the unittests with my changes in ext-phpunit. If you would like to fix these unittests, I can create a PR.

**Comment by oliverklee** [comment]
> If you would like to fix these unittests, I can create a PR.

Yes, please.

**Comment by felixsemmler** [comment]
> > If you would like to fix these unittests, I can create a PR.
> 
> Yes, please.

I had the time to fix the unittests and created a PR:
https://github.com/oliverklee/ext-phpunit/pull/83

**Comment by oliverklee** [comment]
> I had the time to fix the unittests and created a PR:

Thanks a lot! I'll have a look at your PR and then split it into separate PRs.
