### ISSUE TITLE
test database has wrong name 

### ISSUE THREAD

**Issue by hannesbochmann** [oliverklee/ext-phpunit#55]
tested in TYPO3 8.7 and PHP 7.1

The constant TYPO3_db is used for the name of the test database. This must be migrated to $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['dbname']

**Comment by oliverklee** [comment]
@hannesbochmann Could you please test whether PR #58 fixes this problem for you?

**Comment by hannesbochmann** [comment]
That fixed it.
