### ISSUE TITLE
CLI Runner not working since last release (5.3.35)

### ISSUE THREAD

**Issue by hannesbochmann** [oliverklee/ext-phpunit#61]
I'm getting errors like the one below when I want to run tests through CLI:

> Oops, an error occurred: PHP Warning: stat(): stat failed for phar:///var/www/html/webroot/typo3conf/ext/phpunit/Resources/Private/Libraries/phpunit-library.phar/vendor/phpunit/phpunit-selenium/PHPUnit/Runner/StandardTestSuiteLoader.php in /var/www/html/vendor/typo3/cms/typo3/sysext/core/Classes/IO/PharStreamWrapper.php line 519

The tests are invoked like this:
`php /var/www/html/webroot/typo3/cli_dispatch.phpsh phpunit --verbose`

**Comment by oliverklee** [comment]
@hannesbochmann I will have a look at it.

Which TYPO3 version are you using? (For TYPO3 >= 8, please use the new test runner as described here: https://docs.typo3.org/typo3cms/extensions/phpunit/UsersManual/RunningTheUnitTestsOnTheCommandLine/Index.html

**Comment by hannesbochmann** [comment]
I'm using latest TYPO3 7.6

**Comment by oliverklee** [comment]
The warnings are a bug in the Core: https://review.typo3.org/#/c/57595/

**Comment by hannesbochmann** [comment]
Great, thanks for the hint.
