### ISSUE TITLE
CLI options can't be passed to phpunit since TYPO3 8.7

### ISSUE THREAD

**Issue by hannesbochmann** [oliverklee/ext-phpunit#63]
With the new CLI test runner it seems not possible to pass any options like "--verbose" or "-c phpunitBeta.xml". Do I miss something or is it simply not possible in the moment?

**Comment by oliverklee** [comment]
It's probably a missing feature. Would you be willing to provide a PR for this?

**Comment by hannesbochmann** [comment]
I would but I see no easy solution. It seems impossible to let the command accept any argument. So a solution would be to define all arguments that phpunit accepts which are a lot. Another option might be to obtain all arguments in a single string argument and pass that to phpunit.

**Comment by oliverklee** [comment]
> Another option might be to obtain all arguments in a single string argument and pass that to phpunit.

Yes, that sounds like a viable option.

**Comment by hannesbochmann** [comment]
I'm trying to provide a PR.

**Comment by hannesbochmann** [comment]
PR provided.
